# Generated by Django 3.0.6 on 2020-05-28 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roll',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1604001), django.core.validators.MaxValueValidator(1604060)]),
        ),
    ]
