# Generated by Django 3.0.6 on 2020-06-19 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200529_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roll',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(1604001), django.core.validators.MaxValueValidator(1604060)]),
        ),
    ]
