# Generated by Django 3.0.6 on 2020-06-09 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20200607_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_period', models.CharField(max_length=30)),
                ('second_period', models.CharField(max_length=30)),
                ('third_eriod', models.CharField(max_length=30)),
                ('fourth_period', models.CharField(max_length=30)),
                ('fifth_period', models.CharField(max_length=30)),
                ('sixth_period', models.CharField(max_length=30)),
                ('seventh_eriod', models.CharField(max_length=30)),
                ('eigth_period', models.CharField(max_length=30)),
                ('ninth_period', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.TimePeriod')),
            ],
        ),
    ]
