# Generated by Django 3.0.6 on 2020-06-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_routine_timeperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='routine',
        ),
        migrations.AddField(
            model_name='routine',
            name='eigth_period',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='fifth_period',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='first_period',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='fourth_period',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='ninth_period',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='second_period',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='seventh_eriod',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='sixth_period',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='third_eriod',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='day',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1),
        ),
        migrations.DeleteModel(
            name='TimePeriod',
        ),
    ]
