# Generated by Django 3.0.6 on 2020-06-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20200609_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='seventh_eriod',
            new_name='seventh_period',
        ),
        migrations.RenameField(
            model_name='routine',
            old_name='third_eriod',
            new_name='third_period',
        ),
        migrations.AddField(
            model_name='routine',
            name='after_morning_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routine',
            name='afternoon_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routine',
            name='morning_lab',
            field=models.BooleanField(default=False),
        ),
    ]
