# Generated by Django 3.0.6 on 2020-06-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20200609_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='day',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='routine',
            name='eigth_period',
            field=models.CharField(blank=True, default='-', max_length=30, null=' '),
        ),
        migrations.AlterField(
            model_name='routine',
            name='fifth_period',
            field=models.CharField(blank=True, default='-', max_length=30, null=' '),
        ),
        migrations.AlterField(
            model_name='routine',
            name='first_period',
            field=models.CharField(blank=True, default='-', max_length=30, null=' '),
        ),
        migrations.AlterField(
            model_name='routine',
            name='fourth_period',
            field=models.CharField(blank=True, default='-', max_length=30, null=' '),
        ),
        migrations.AlterField(
            model_name='routine',
            name='ninth_period',
            field=models.CharField(blank=True, default='-', max_length=30, null=' '),
        ),
        migrations.AlterField(
            model_name='routine',
            name='second_period',
            field=models.CharField(blank=True, default='-', max_length=30, null=' '),
        ),
        migrations.AlterField(
            model_name='routine',
            name='seventh_period',
            field=models.CharField(blank=True, default='-', max_length=30, null=' '),
        ),
        migrations.AlterField(
            model_name='routine',
            name='sixth_period',
            field=models.CharField(blank=True, default='-', max_length=30, null=' '),
        ),
        migrations.AlterField(
            model_name='routine',
            name='third_period',
            field=models.CharField(blank=True, default='-', max_length=30, null=' '),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1),
        ),
    ]
